FROM alpine:3.20

RUN apk add --no-cache \
        build-base \
        git \
        linux-headers

WORKDIR /opt

RUN git clone https://github.com/ffainelli/easy-smart-config.git \
    && cd easy-smart-config \
    && make \
    && install -m 0755 easy-smart-config /usr/local/bin/easy-smart-config \
    && cd /opt \
    && rm -rf easy-smart-config \
    && apk del build-base git linux-headers

ENTRYPOINT ["/usr/local/bin/easy-smart-config"]
