version: "3.9"

services:
  easy-smart-config:
    container_name: easy-smart-config
    build:
      context: .
      dockerfile: Containerfile
    network_mode: host
    command: ["/bin/sh", "-c", "sleep infinity"]
    restart: "no"
